@extends('layouts.app')
@section('title', 'Staff audit history')
@section('content')
<section class="page-hero compact"><div class="shell"><a class="back-link" href="{{ route('admin.dashboard') }}">← Operations dashboard</a><span class="eyebrow">Operations history</span><h1>Staff audit log</h1><p>Recorded stock, payment, order, refund and repair actions.</p></div></section>
<div class="shell admin-history-layout">
    <form class="clay-card audit-filters" method="GET" action="{{ route('admin.audit') }}"><label>Action<select name="action"><option value="">All actions</option>@foreach($actions as $action)<option value="{{ $action }}" @selected(request('action') === $action)>{{ str_replace(['.', '_'], ' ', $action) }}</option>@endforeach</select></label><label>Actor<select name="user_id"><option value="">All actors</option>@foreach($actors as $actor)<option value="{{ $actor->id }}" @selected(request('user_id') == $actor->id)>{{ $actor->name }}</option>@endforeach</select></label><label>Entity<select name="entity_type"><option value="">All entities</option>@foreach(['Order', 'Product', 'Refund', 'RepairBooking', 'Review'] as $type)<option value="{{ $type }}" @selected(request('entity_type') === $type)>{{ $type }}</option>@endforeach</select></label><label>Date<input type="date" name="date" value="{{ request('date') }}"></label><button class="btn btn-primary" type="submit">Filter history</button></form>
    <section class="clay-card table-card"><h2>Recorded actions</h2><div class="table-scroll"><table><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Entity</th><th>Changes</th><th>Reason</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ $log->created_at?->format('M j, Y · g:i A') }}</td><td>{{ $log->actor?->name ?? 'System' }}</td><td><strong>{{ str_replace(['.', '_'], ' ', $log->action) }}</strong></td><td>{{ $log->auditable_type }} #{{ $log->auditable_id }}</td><td><small>Before: {{ $log->old_values ? json_encode($log->old_values, JSON_UNESCAPED_UNICODE) : '—' }}</small><small>After: {{ $log->new_values ? json_encode($log->new_values, JSON_UNESCAPED_UNICODE) : '—' }}</small></td><td>{{ $log->reason ?? '—' }}</td></tr>@empty<tr><td colspan="6">No audit entries match these filters.</td></tr>@endforelse</tbody></table></div></section>
    {{ $logs->links() }}
</div>
@endsection
