@extends('layouts.app')
@section('title', 'Operations dashboard')
@section('content')
<section class="page-hero compact"><div class="shell"><span class="eyebrow">Mobile Arena operations</span><h1>Orders, inventory and repairs</h1><p>Review fulfillment, stock movements and customer requests.</p><div class="operations-links"><a class="btn btn-secondary" href="{{ route('admin.products.index') }}">Manage products</a><a class="btn btn-secondary" href="{{ route('admin.reviews.index') }}">Reviews</a><a class="btn btn-secondary" href="{{ route('admin.refunds.index') }}">Refund reviews</a><a class="btn btn-secondary" href="{{ route('admin.audit') }}">Audit history</a></div></div></section>
<div class="shell admin-stats">@foreach($stats as $label => $value)<div class="stat-card clay-card"><span>{{ str_replace('_', ' ', ucfirst($label)) }}</span><strong>{{ $value }}</strong></div>@endforeach</div>
<div class="shell admin-grid">
    <section class="table-card clay-card"><div class="account-section-head"><h2>Recent orders</h2><span class="microcopy">Open an order for fulfillment details.</span></div><div class="table-scroll"><table><thead><tr><th>Order</th><th>Customer</th><th>Total / payment</th><th>Status</th><th>Action</th></tr></thead><tbody>
        @forelse($orders as $order)<tr><td><strong><a href="{{ route('admin.orders.show', $order) }}">{{ $order->reference }}</a></strong><small>{{ $order->created_at->format('M j, Y') }}</small></td><td>{{ $order->customer_name }}<small>{{ $order->user?->email ?? $order->email ?? 'Legacy customer' }}</small></td><td>₱{{ number_format($order->total, 2) }}<small>{{ $order->payment_method_label }} · {{ $order->payment_status_label }}</small></td><td><span class="status-pill">{{ $order->status_label }}</span></td><td><a class="btn btn-secondary" href="{{ route('admin.orders.show', $order) }}">Review</a></td></tr>
        @empty<tr><td colspan="5">No orders yet.</td></tr>@endforelse
    </tbody></table></div></section>
    <section class="table-card clay-card"><h2>Product inventory</h2><p class="microcopy">Physical stock includes reserved units. Available stock is physical stock minus active reservations. Scroll the table sideways on small screens.</p><div class="table-scroll"><table><thead><tr><th>Product</th><th>Physical</th><th>Reserved</th><th>Available</th><th>Status</th><th>Adjustment</th><th>History</th></tr></thead><tbody>
        @forelse($products as $product)<tr><td><strong>{{ $product->name }}</strong><small>{{ $product->sku }}</small></td><td>{{ $product->stock }}</td><td>{{ $product->reserved_stock }}</td><td>{{ $product->available_stock }}</td><td><span class="status-pill">{{ $product->available_stock === 0 ? 'Out of Stock' : ($product->available_stock <= config('mobile-arena.inventory.low_stock_threshold') ? 'Low Stock' : 'In Stock') }}</span></td><td><form class="stock-update-form" method="POST" action="{{ route('admin.products.stock', $product) }}">@csrf @method('PATCH')<label class="sr-only" for="stock-{{ $product->id }}">Physical stock for {{ $product->name }}</label><input id="stock-{{ $product->id }}" name="stock" type="number" min="{{ $product->reserved_stock }}" max="4294967295" value="{{ $product->stock }}" required><label class="sr-only" for="stock-type-{{ $product->id }}">Movement type</label><select id="stock-type-{{ $product->id }}" name="movement_type"><option value="adjustment">Adjustment</option><option value="correction">Correction</option><option value="damage">Damage</option></select><label class="sr-only" for="stock-reason-{{ $product->id }}">Reason</label><input id="stock-reason-{{ $product->id }}" name="reason" placeholder="Reason required" minlength="3" maxlength="500" required><button class="btn btn-secondary" type="submit">Save</button></form></td><td><a href="{{ route('admin.products.history', $product) }}">Movements</a></td></tr>
        @empty<tr><td colspan="7">No products yet.</td></tr>@endforelse
    </tbody></table></div></section>
    <section class="table-card clay-card"><div class="account-section-head"><h2>Refund requests</h2><a href="{{ route('admin.refunds.index') }}">View all</a></div><div class="table-scroll"><table><thead><tr><th>Order</th><th>Status</th><th>Amount</th><th>Action</th></tr></thead><tbody>@forelse($refunds as $refund)<tr><td>{{ $refund->order->reference }}</td><td>{{ $refund->status_label }}</td><td>₱{{ number_format((float) $refund->amount, 2) }}</td><td><a href="{{ route('admin.refunds.index') }}">Review</a></td></tr>@empty<tr><td colspan="4">No refund requests yet.</td></tr>@endforelse</tbody></table></div></section>
    <section class="table-card clay-card"><h2>Repair requests</h2><div class="table-scroll"><table><thead><tr><th>Reference</th><th>Customer / device</th><th>Status and technician update</th></tr></thead><tbody>
        @forelse($repairs as $repair)<tr><td><strong>{{ $repair->reference }}</strong><small>{{ $repair->created_at->format('M j, Y') }}</small></td><td>{{ $repair->customer_name }}<small>{{ $repair->user?->email ?? $repair->brand_model }}</small><small>{{ $repair->brand_model }}</small></td><td><form class="admin-status-form" method="POST" action="{{ route('admin.repairs.update', $repair) }}">@csrf @method('PATCH')<label class="sr-only" for="repair-status-{{ $repair->id }}">Repair status</label><select id="repair-status-{{ $repair->id }}" name="status">@foreach(\App\Models\RepairBooking::STATUS_LABELS as $value => $label)<option value="{{ $value }}" @selected($repair->status === $value || ($repair->status === 'requested' && $value === 'pending'))>{{ $label }}</option>@endforeach</select><input name="estimated_cost" type="number" min="0" step="0.01" value="{{ $repair->estimated_cost }}" aria-label="Estimated cost for {{ $repair->reference }}" placeholder="Estimated ₱"><textarea name="technician_notes" rows="2" aria-label="Customer-visible technician notes for {{ $repair->reference }}" placeholder="Customer-visible technician notes">{{ $repair->technician_notes }}</textarea><button class="btn btn-secondary" type="submit">Save</button></form></td></tr>
        @empty<tr><td colspan="3">No requests yet.</td></tr>@endforelse
    </tbody></table></div></section>
</div>
@endsection
