@extends('layouts.app')
@section('title', 'Review moderation')
@section('content')
<section class="page-hero compact"><div class="shell"><span class="eyebrow">Mobile Arena operations</span><h1>Product reviews</h1><p>Hide or restore customer reviews. Every moderation change is audited.</p><div class="operations-links"><a class="btn btn-secondary" href="{{ route('admin.dashboard') }}">Dashboard</a><a class="btn btn-secondary" href="{{ route('admin.products.index') }}">Products</a></div></div></section>
<div class="shell admin-history-layout"><form class="clay-card review-moderation-filter" method="GET" action="{{ route('admin.reviews.index') }}"><label for="review-status">Visibility</label><select id="review-status" name="status"><option value="">All reviews</option><option value="published" @selected($status === 'published')>Published</option><option value="hidden" @selected($status === 'hidden')>Hidden</option></select><button class="btn btn-primary" type="submit">Apply</button></form>
    @forelse($reviews as $review)<article class="clay-card review-card"><div class="review-card-head"><div><strong>{{ $review->product?->name ?? 'Historic product' }}</strong><p>{{ $review->display_name }} · {{ $review->orderItem?->order?->reference ?? 'Order unavailable' }}</p></div><span class="status-pill">{{ ucfirst($review->status) }}</span></div><div class="review-stars" aria-label="{{ $review->rating }} out of 5 stars">{{ str_repeat('★', $review->rating) }}</div>@if($review->title)<h2>{{ $review->title }}</h2>@endif<p>{{ $review->body }}</p><small>{{ $review->created_at->format('M j, Y g:i A') }}</small><form method="POST" action="{{ route('admin.reviews.moderate', $review) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $review->status === 'published' ? 'hidden' : 'published' }}"><button class="btn btn-secondary" type="submit">{{ $review->status === 'published' ? 'Hide review' : 'Restore review' }}</button></form></article>@empty<div class="empty-state clay-card"><h2>No reviews here</h2><p>Reviews will appear when customers rate completed purchases.</p></div>@endforelse
    {{ $reviews->links() }}
</div>
@endsection
