@extends('layouts.app')
@section('title', $product->exists ? 'Edit product' : 'Add product')
@section('content')
<section class="page-hero compact"><div class="shell"><span class="eyebrow">Mobile Arena catalog</span><h1>{{ $product->exists ? 'Edit product' : 'Add product' }}</h1><p>Describe the item accurately. Add unit-specific details for pre-owned or refurbished stock when available.</p></div></section>
<div class="shell admin-history-layout"><a class="back-link" href="{{ route('admin.products.index') }}">← All products</a><div class="clay-card product-admin-form"><form method="POST" action="{{ $product->exists ? route('admin.products.update', $product) : route('admin.products.store') }}">@csrf @if($product->exists)@method('PATCH')@endif
    <h2>Product information</h2><div class="product-form-grid">
        <label for="product-name">Name <span>*</span><input id="product-name" name="name" required maxlength="255" value="{{ old('name', $product->name) }}"></label>
        <label for="product-sku">SKU <span>*</span><input id="product-sku" name="sku" required maxlength="120" value="{{ old('sku', $product->sku) }}"></label>
        <label for="product-brand">Brand <span>*</span><input id="product-brand" name="brand" required maxlength="120" value="{{ old('brand', $product->brand) }}"></label>
        <label for="product-model">Model <small>optional</small><input id="product-model" name="model_name" maxlength="150" value="{{ old('model_name', $product->model_name) }}"></label>
        <label for="product-category">Category <span>*</span><select id="product-category" name="category_id" required><option value="">Choose category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></label>
        <label for="product-condition">Condition <span>*</span><select id="product-condition" name="condition" required><option value="">Choose condition</option><option value="brand_new" @selected(old('condition', $product->condition) === 'brand_new')>Brand New</option><option value="pre_owned" @selected(old('condition', $product->condition) === 'pre_owned')>Pre-Owned</option><option value="refurbished" @selected(old('condition', $product->condition) === 'refurbished')>Refurbished</option></select></label>
        <label for="product-grade">Cosmetic grade <small>if applicable</small><input id="product-grade" name="grade" maxlength="80" value="{{ old('grade', $product->grade) }}"></label>
        <label for="product-slug">URL slug <small>optional when adding</small><input id="product-slug" name="slug" maxlength="255" value="{{ old('slug', $product->slug) }}" placeholder="Generated from name if blank"></label>
        <label for="product-price">Price (₱) <span>*</span><input id="product-price" name="price" type="number" min="0" max="9999999999.99" step="0.01" required value="{{ old('price', $product->price) }}"></label>
        <label for="product-compare-price">Compare price (₱) <small>optional</small><input id="product-compare-price" name="compare_price" type="number" min="0" max="9999999999.99" step="0.01" value="{{ old('compare_price', $product->compare_price) }}"></label>
        <label class="span-2" for="product-short">Short description <span>*</span><input id="product-short" name="short_description" required maxlength="255" value="{{ old('short_description', $product->short_description) }}"></label>
        <label class="span-2" for="product-description">Description<textarea id="product-description" name="description" rows="5" maxlength="10000">{{ old('description', $product->description) }}</textarea></label>
        <label class="span-2" for="product-warranty">Warranty or condition note<input id="product-warranty" name="warranty_note" maxlength="255" value="{{ old('warranty_note', $product->warranty_note) }}"></label>
        <label class="span-2" for="product-specs">Specifications <small>one Label: Value per line; include battery, accessories or known issues only when verified</small><textarea id="product-specs" name="specifications_text" rows="6">{{ old('specifications_text', collect($product->specifications ?? [])->map(fn($value, $key) => $key.': '.(is_array($value) ? implode(', ', $value) : $value))->implode("\n")) }}</textarea></label>
    </div>
    <h2>Images</h2><p class="microcopy">Use an HTTPS image URL or a path under public/images. Add one gallery image per line, up to six.</p><div class="product-form-grid"><label class="span-2" for="product-image">Main image<input id="product-image" name="image" maxlength="255" value="{{ old('image', $product->image) }}" placeholder="products/phone.jpg or https://…"></label><label class="span-2" for="product-images">Gallery images<textarea id="product-images" name="images_text" rows="4">{{ old('images_text', implode("\n", $product->images ?? [])) }}</textarea></label></div>
    <h2>Storefront</h2><div class="product-form-grid"><label for="product-active">Visibility<select id="product-active" name="active"><option value="1" @selected(old('active', $product->active ?? true) == 1)>Active — visible to customers</option><option value="0" @selected(old('active', $product->active ?? true) == 0)>Inactive — hidden from storefront</option></select></label><label for="product-featured">Homepage feature<select id="product-featured" name="featured"><option value="0" @selected(old('featured', $product->featured ?? false) == 0)>Standard listing</option><option value="1" @selected(old('featured', $product->featured ?? false) == 1)>Featured listing</option></select></label></div>
    @unless($product->exists)<h2>Opening inventory</h2><p class="microcopy">Opening stock is recorded in inventory history. Later changes use the inventory dashboard.</p><div class="product-form-grid"><label for="opening-stock">Physical units <span>*</span><input id="opening-stock" type="number" name="opening_stock" min="0" max="4294967295" required value="{{ old('opening_stock', 0) }}"></label><label for="stock-reason">Reason for opening stock<input id="stock-reason" name="stock_reason" maxlength="500" value="{{ old('stock_reason') }}" placeholder="Required when stock is greater than zero"></label></div>@else<p class="microcopy">Physical stock: {{ $product->stock }} · Reserved: {{ $product->reserved_stock }} · Available: {{ $product->available_stock }}. <a href="{{ route('admin.dashboard') }}">Adjust stock in the inventory dashboard</a>.</p>@endunless
    <div class="form-submit"><button class="btn btn-primary" type="submit">{{ $product->exists ? 'Save product' : 'Create product' }}</button><a class="btn btn-secondary" href="{{ route('admin.products.index') }}">Cancel</a></div>
    </form></div></div>
@endsection
